SANDBOX_SCHEMA = [
    {"name": "coin_id", "type": "STRING", "mode": "REQUIRED"},
    {"name": "symbol", "type": "STRING", "mode": "REQUIRED"},
    {"name": "name", "type": "STRING", "mode": "NULLABLE"},
    {"name": "current_price", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "market_cap", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "market_cap_rank", "type": "INT64", "mode": "NULLABLE"},
    {"name": "total_volume", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "high_24h", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "low_24h", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "price_change_24h", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "price_change_percentage_24h", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "circulating_supply", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "total_supply", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "max_supply", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "ath", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "ath_change_percentage", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "ath_date", "type": "STRING", "mode": "NULLABLE"},
    {"name": "atl", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "atl_change_percentage", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "atl_date", "type": "STRING", "mode": "NULLABLE"},
    {"name": "last_updated", "type": "STRING", "mode": "NULLABLE"},
    {"name": "source", "type": "STRING", "mode": "REQUIRED"},
    {"name": "vs_currency", "type": "STRING", "mode": "REQUIRED"},
    {"name": "ingestion_date", "type": "DATE", "mode": "REQUIRED"},
    {"name": "ingested_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
]


INTEGRATION_SCHEMA = [
    {"name": "coin_id", "type": "STRING", "mode": "REQUIRED"},
    {"name": "symbol", "type": "STRING", "mode": "REQUIRED"},
    {"name": "name", "type": "STRING", "mode": "NULLABLE"},
    {"name": "snapshot_date", "type": "DATE", "mode": "REQUIRED"},
    {"name": "current_price", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "market_cap", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "market_cap_rank", "type": "INT64", "mode": "NULLABLE"},
    {"name": "total_volume", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "high_24h", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "low_24h", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "price_change_24h", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "price_change_percentage_24h", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "circulating_supply", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "total_supply", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "max_supply", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "ath", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "ath_change_percentage", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "ath_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
    {"name": "atl", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "atl_change_percentage", "type": "FLOAT64", "mode": "NULLABLE"},
    {"name": "atl_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
    {"name": "last_updated", "type": "TIMESTAMP", "mode": "NULLABLE"},
    {"name": "source", "type": "STRING", "mode": "REQUIRED"},
    {"name": "vs_currency", "type": "STRING", "mode": "REQUIRED"},
    {"name": "execution_date", "type": "DATE", "mode": "REQUIRED"},
    {"name": "ingested_at", "type": "TIMESTAMP", "mode": "REQUIRED"},
]